name: Team approval workflow
on: pull_request_review
jobs:
  labelWhenApprovated:
    run-on: ubuntu-latest
    step:
    - name: Label approved pull requests
      uses: abinoda/label-when-approved-action@v1.0.7
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
        
